{% set version = "3.6.0" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/p/pytest-django/pytest-django-{{ version }}.tar.gz
  sha256: b6c900461a6a7c450dcf11736cabc289a90f5d6f28ef74c46e32e86ffd16a4bd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.11.1
    - pathlib
    - pytest >=3.6
  run:
    - python
    - pytest >=3.6

test:
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
