{% set version = "3.5.1" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/p/pytest-django/pytest-django-{{ version }}.tar.gz
  sha256: 264fb4c506db5d48a6364c311a0b00b7b48a52715bad8839b2d8bee9b99ed6bb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.11.1
    - pathlib
    - pytest >=3.6
  run:
    - python
    - pytest >=3.6

test:
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
