{% set version = "3.4.1" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/p/pytest-django/pytest-django-{{ version }}.tar.gz
  sha256: 85f840e319d7b4271d6f1a3d95c0fb900c7183f7a4414e0cceed75f92bf3bc75
  patches:
    - setuptools_scm.patch

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.11.1
    - pytest >=3.6
  run:
    - python
    - pytest >=3.6

test:
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
