{% set version = "3.2.1" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  fn: pytest-django-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/p/pytest-django/pytest-django-{{ version }}.tar.gz
  sha256: 7501942093db2250a32a4e36826edfc542347bb9b26c78ed0649cdcfd49e5789
  patches:
    # setup_requires is throwing errors in setuptools
    - setuptools_scm.patch

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest >=2.9

test:
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
