{% set version = "3.9.0" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-django/pytest-django-{{ version }}.tar.gz
  sha256: 664e5f42242e5e182519388f01b9f25d824a9feb7cd17d8f863c8d776f38baf9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.11.1
    - pathlib
    - pytest >=3.6
  run:
    - python
    - pytest >=3.6

test:
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
