{% set version = "3.10.0" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-django/pytest-django-{{ version }}.tar.gz
  sha256: 4de6dbd077ed8606616958f77655fed0d5e3ee45159475671c7fa67596c6dba6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.11.1
    - pathlib
  run:
    - python
    - pytest >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
