travis:
  secure:
    BINSTAR_TOKEN: XaSjo0sCaH+4NaiOPYnMH6MawwmwdkVWWuPUgo5rydQ9Z4su+LU433HKPDOrBjYCgGsyEuG2C0lL1F0qEHX5bRUA9vQbtQDORdMYvapcH28Z18t1bODBmfyq6knIx/YIds/7y+aG+i/qKujES/hI33lT2l6+9/nbUYv/6iIo4SRdoduv3pt21bKxx2T0ZdA1yHRJAyDt3J/JyHS8QcousJmU1LFsY/3zTcUrgfyM7YyZV/+eaw3u/HolhKKfg3WrUH9PAKcq8rEJgNSEHzMV2q/zb3IcnFEACEIquE1usIN6djEcLsPDBRG/vLctdqHVjI/BBaZo7U/6OA2RD1CJl2rM+RTBihKS1mGrLdSOjyoJmX4gzKC6sB/OIDjtKOUnRZdKJ3f/B5XUzmemHv/GG4xr7e6Eis4PI3xnOi5dqJwXJpYvdQURelttbkGN/St33P4OZE4FRovpItoLlQyOZ7EPInPJlGYwBnEaTH6/0cLymOFgFfJY7vqn+JVNcnrcrqeX7Om6vlQpzfs+6wcboAH6A7FUf54wBVt5fF7c7wFK8IiibchMWDBZi/sDmkZ7kNWhBsKJS71+cWF9QrLSuIAfQr2lCFLMUcF+g2APQNRdWckLTSsLcMqNnFrFBNC4Vwza1XG7wCtXxYUaln+IgAqnLOhuOtnmpfLd1fcQ//c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
