travis:
  secure:
    BINSTAR_TOKEN: Jh65fW09w2mkz8x6Fc/HiN3NuVgOALFUogKpBk4jPUtBqHl2ch9bce1XneJaQOC/J0XBN0bKR6z1/3zp/f0uOXXy3q70/4qHbGYjtMQJT8o2illaJtDB4J/6iMbaoerg0K73L61zW2IaPta2uxPmVNdCVPAwjHxooB/p06IYpA3UJ/YcORFSHOP1E1MCP+UQE5Q5NXqNDwrybDrz3F8dJO6hd15tnYPNOJSbGy3fS3WhbNTGtZQLu0YV6HvxQknd7494G3xB/2xSaJ4XMkKL+yQ+9s8OFmvH9yPX+WFq//hXqbmzc9kpg6+b9Pq3B91zGdPRuwa1gGOMa4g8B8NtVJpyBH/xff/9MhJs4oJfciKQ6+aZ/CSavRh7eIUA5GAkXD0uZ104vfwHiMi02S+QbA56tSf8SsCEr7EtvxKSt55nsP54jT1TmzBKjnsD0rS2iH5Cx0lPBEBZkvsG+IoxWnQb3vDYmSosq5xzgzcZJJ6vpeXZsL9myDgtqStttZqhErLOD+p4DtNuyYy5LcwiAmf+LzJXCfUM9AfnUegDZMAk9LFFNW2A5PGMRjojhemo6Epl68NVdg5tEKXJtWlDrauGuiBd79nYM/fXg0NBReqMUXUU/sm+5MAkRvAx8Eqf5M8jN0RnWtSr8tHlkg/ebLQHbM4tscmQ3Bje8ZIlrSU=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
