travis:
  secure:
    BINSTAR_TOKEN: dJXti8kYqHKnBWsHYLrCVXxT15e/kksuihHNODF0YW9PmZFns2PO318lnEKPXefFggVusvQZgTzy29XMafDjtXgIOEOZWYqfz9em8nsw9ZjgVfmIms9P47hD4eN/NfqkWWogk5+Log30SNytmkHiTyEhcZiV/VIim8j8k2gZroStxK4Nt6nKoCdZHsugiZigU9YaqqgUSQxRxldAml2nzoAro4HwlOTbDnWDwZNBVA0BukzrfOcMuWZA0Bmbcj6bntpyO60fKWHN98uPmVivgfWN3OQ+FVSXeWKmOD4Mp7ioJnvCEEjYdXMw6neNav8/lcRbpvzLB1l0ZZmYm55uVaRjXmz52dVqO8NjcNjfL6oIUPQJPZVi2ne/JK109bNVs0c9n24tnC+b1MTEfFD+v9VEk7wyJz/qh0nU60Ula8KG139iNhagmeTFalwAUxHTl0d4iLnOZKKWOHqTMLGE9+NPkZL2rIADPIY4L5U3Y6bd6UWFhNTk0h/rTiCtcW4s7qfjZpo8oPuwme/MIEmGjPUfgZ/fl0//Zjw61SKSZuu4K7Z9OaRJg3L4geXgqWiMZgfT6Ya58Mn1J+YCR3gz38pC4CcbCc58s9xxM+0Z9dAR+TBnql5x4FJ4OKVFsm2xVLpHXXLmk5aWGY50B0awIJsA5Qr69aVzu7nAvJptz+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
